name: GDUnit4 CI

on:
  push:
  # Trigger tests on every push to any branch
    branches: [ "**" ]
  pull_request:
    # Trigger tests when merge into main
    branches: [ "prod" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute tests
        uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: '4.6.1'
          paths: 'res://tests'
          timeout: 5
          publish-report: false